# Generated by Django 5.0.7 on 2026-05-19 07:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название помещения')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступно для бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Дата проведения конференции')),
                ('conference_start', models.DateTimeField(blank=True, null=True, verbose_name='Предпочтительное время начала конференции')),
                ('payment_method', models.CharField(choices=[('card', 'Оплата картой МИР'), ('transfer', 'Постоплата в офисе организации'), ('qrcode', 'Предоплата по QR-коду')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('assigned', 'Мероприятие назначено'), ('completed', 'Мероприятие завершено'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заявке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='booking.room', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только кириллицу, пробелы и дефис', regex='^[А-Яа-яЁё\\s-]+$')], verbose_name='ФИО')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате 8(XXX)XXX-XX-XX', regex='^8\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва')),
                ('booking_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking.bookingrequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
